# Stage 1: Build backend
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . ./

# Stage 2: Production image
FROM node:20-alpine
WORKDIR /app
COPY --from=build /app ./
EXPOSE 5003
CMD ["npm", "start"]
